-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 17:30:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nivel` (
  `idNivel` INT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(45) NULL,
  PRIMARY KEY (`idNivel`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TipoPerfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoPerfil` (
  `idTipoPerfil` INT NULL AUTO_INCREMENT,
  `tipoPerfil` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoPerfil`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfiles` (
  `idPerfiles` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcionPerfil` VARCHAR(500) NULL,
  `Nivel_idNivel` INT NOT NULL,
  `TipoPerfil_idTipoPerfil` INT NOT NULL,
  PRIMARY KEY (`idPerfiles`, `Nivel_idNivel`, `TipoPerfil_idTipoPerfil`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Condiciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Condiciones` (
  `id_Condiciones` INT NULL AUTO_INCREMENT,
  `condidion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id_Condiciones`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Plazas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Plazas` (
  `idPlaza` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(500) NULL,
  `curriculum` VARCHAR(150) NULL,
  `Perfiles_idPerfiles` INT NOT NULL,
  `Perfiles_Nivel_idNivel` INT NOT NULL,
  `Perfiles_TipoPerfil_idTipoPerfil` INT NOT NULL,
  `Condiciones_id_Condiciones` INT NOT NULL,
  PRIMARY KEY (`idPlaza`, `Perfiles_idPerfiles`, `Perfiles_Nivel_idNivel`, `Perfiles_TipoPerfil_idTipoPerfil`, `Condiciones_id_Condiciones`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empleados` (
  `id_Empleado` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `Plazas_idPlaza` INT NOT NULL,
  `Plazas_Perfiles_idPerfiles` INT NOT NULL,
  `Plazas_Perfiles_Nivel_idNivel` INT NOT NULL,
  `Plazas_Perfiles_TipoPerfil_idTipoPerfil` INT NOT NULL,
  `Plazas_Condiciones_id_Condiciones` INT NOT NULL,
  PRIMARY KEY (`id_Empleado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Departamentos` (
  `idDepartamento` INT NULL AUTO_INCREMENT,
  `nombreDep` VARCHAR(45) NULL,
  `Plazas_idPlaza` INT NOT NULL,
  `Plazas_Perfiles_idPerfiles` INT NOT NULL,
  `Plazas_Perfiles_Nivel_idNivel` INT NOT NULL,
  `Plazas_Perfiles_TipoPerfil_idTipoPerfil` INT NOT NULL,
  `Plazas_Condiciones_id_Condiciones` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`, `Plazas_idPlaza`, `Plazas_Perfiles_idPerfiles`, `Plazas_Perfiles_Nivel_idNivel`, `Plazas_Perfiles_TipoPerfil_idTipoPerfil`, `Plazas_Condiciones_id_Condiciones`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoUsuario` (
  `id_TipoUsuario` INT NULL AUTO_INCREMENT,
  `TipoUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_TipoUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tbl_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_Usuarios` (
  `id_Usuarios` INT NULL AUTO_INCREMENT,
  `nomber` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `TipoUsuario_id_TipoUsuario` INT NOT NULL,
  PRIMARY KEY (`id_Usuarios`, `TipoUsuario_id_TipoUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
